/**
 * Communes valaisannes officielles (122) + localités courantes.
 * Source : liste des communes du canton du Valais.
 * Les localités (Verbier, Anzère, etc.) sont incluses car c’est ce que
 * les propriétaires tapent réellement.
 */
export const COMMUNES_VALAIS: string[] = [
  "Agarn",
  "Aminona",
  "Anniviers",
  "Anzère",
  "Aproz",
  "Arbaz",
  "Arbignon",
  "Ardon",
  "Arolla",
  "Ausserberg",
  "Ayer",
  "Ayent",
  "Baltschieder",
  "Bellwald",
  "Bettmeralp",
  "Binn",
  "Bister",
  "Bitsch",
  "Blatten",
  "Bourg-Saint-Pierre",
  "Bovernier",
  "Bramois",
  "Brigue-Glis",
  "Brig-Glis",
  "Bruson",
  "Bürchen",
  "Chalais",
  "Chamoson",
  "Champéry",
  "Champoussin",
  "Champex-Lac",
  "Chandolin",
  "Charrat",
  "Chermignon",
  "Chippis",
  "Collombey-Muraz",
  "Collonges",
  "Conthey",
  "Crans",
  "Crans-Montana",
  "Dorénaz",
  "Eggerberg",
  "Eischoll",
  "Eisten",
  "Embd",
  "Erde",
  "Ergisch",
  "Ernen",
  "Evionnaz",
  "Evolène",
  "Ferden",
  "Fiesch",
  "Fieschertal",
  "Finhaut",
  "Fully",
  "Gampel-Bratsch",
  "Goms",
  "Grächen",
  "Grengiols",
  "Grimentz",
  "Grimisuat",
  "Grône",
  "Guttet-Feschel",
  "Haute-Nendaz",
  "Hérémence",
  "Icogne",
  "Inden",
  "Isérables",
  "Kippel",
  "La Forclaz",
  "Lalden",
  "Lax",
  "Le Châble",
  "Lens",
  "Les Collons",
  "Les Crosets",
  "Les Haudères",
  "Leuk",
  "Leukerbad",
  "Leytron",
  "Liddes",
  "Loèche",
  "Loèche-les-Bains",
  "Martigny",
  "Martigny-Combe",
  "Mase",
  "Massongex",
  "Miège",
  "Montana",
  "Mont-Noble",
  "Monthey",
  "Mörel-Filet",
  "Morgins",
  "Nax",
  "Naters",
  "Nendaz",
  "Niedergesteln",
  "Noble-Contrée",
  "Oberems",
  "Obergoms",
  "Orsières",
  "Port-Valais",
  "Randa",
  "Randogne",
  "Rarogne",
  "Raron",
  "Riddes",
  "Ried-Brig",
  "Riederalp",
  "Saas-Almagell",
  "Saas-Balen",
  "Saas-Fee",
  "Saas-Grund",
  "Saillon",
  "Saint-Gingolph",
  "Saint-Léonard",
  "Saint-Luc",
  "Saint-Martin",
  "Saint-Maurice",
  "Saint-Nicolas",
  "Salgesch",
  "Salins",
  "Salquenen",
  "Salvan",
  "Savièse",
  "Saxon",
  "Sembrancher",
  "Sierre",
  "Simplon",
  "Sion",
  "Siviez",
  "Stalden",
  "Staldenried",
  "Steg-Hohtenn",
  "St. Niklaus",
  "Täsch",
  "Termen",
  "Thyon",
  "Törbel",
  "Trient",
  "Troistorrents",
  "Turtmann-Unterems",
  "Unterbäch",
  "Uvrier",
  "Val de Bagnes",
  "Val-d'Illiez",
  "Varen",
  "Varonne",
  "Venthône",
  "Verbier",
  "Vernamiège",
  "Vernayaz",
  "Vérossaz",
  "Vétroz",
  "Vex",
  "Veyras",
  "Veysonnaz",
  "Viège",
  "Vionnaz",
  "Visp",
  "Visperterminen",
  "Vissoie",
  "Vollèges",
  "Vouvry",
  "Wiler",
  "Zeneggen",
  "Zermatt",
  "Zinal",
  "Zwischbergen",
];

export function normalizeCommune(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
}

export function filterCommunes(query: string, limit = 8): string[] {
  const needle = normalizeCommune(query);
  if (!needle) return [];

  const startsWith: string[] = [];
  const includes: string[] = [];

  for (const commune of COMMUNES_VALAIS) {
    const hay = normalizeCommune(commune);
    if (hay.startsWith(needle)) startsWith.push(commune);
    else if (hay.includes(needle)) includes.push(commune);
    if (startsWith.length >= limit) break;
  }

  return [...startsWith, ...includes].slice(0, limit);
}
